name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build
        run: go build -v .

      - name: Create Release
        id: create_release
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }} # replace MY_PAT with the name of your secret
        with:
          args: |
            ${{ github.ref }}
            Release ${{ github.ref }}
            false
            false

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }} # replace MY_PAT with the name of your secret
        with:
          files: ./main # replace with the path to your asset
